name: "PR Checks"
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        name: Action Test
        steps:
            - uses: actions/checkout@v1
            - uses: ./
              with:
                username: ${{ secrets.SAUCE_USERNAME }}
                accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
                tunnelIdentifier: github-action-tunnel

            - name: "Install Dependencies"
              run: npm install

            - name: "Run Test"
              run: npm run test
              env:
                SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
                SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
    verify-artifact:
        runs-on: ubuntu-latest
        name: Verify the SC log is uploaded as artifact
        needs: test
        steps:
            - uses: actions/download-artifact@v2
              with:
                name: source-connect-logs
                path: .
            - run: |
                if [ -f "sauce-connect.log" ]; then
                  echo verified that sauce-connect.log exists in the uploaded artifact
                else
                  echo no sauce-connect.log found in the uploaded artifact
                  exit 1
                fi

